# Generated by Django 4.2.3 on 2023-07-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board", name="body", field=models.TextField(default="default"),
        ),
    ]
