# Generated by Django 4.2.3 on 2023-07-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_remove_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
