# Generated by Django 4.2.3 on 2023-07-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_comment_board"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="comment", new_name="content",
        ),
    ]
