# Generated by Django 4.2.3 on 2023-07-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0009_rename_comment_comment_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="content", new_name="comment",
        ),
    ]
