# Generated by Django 4.2.3 on 2023-07-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0010_rename_content_comment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="user", new_name="nickname",
        ),
        migrations.RemoveField(model_name="comment", name="board",),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="board.board",
            ),
        ),
    ]
