# Generated by Django 4.2.3 on 2023-07-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0011_rename_user_comment_nickname_remove_comment_board_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="post",),
    ]
