# Generated by Django 4.2.3 on 2023-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0013_comment_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="post",),
    ]
