# Generated by Django 4.2.3 on 2023-07-08 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0016_remove_comment_nickname_comment_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="user",),
        migrations.AddField(
            model_name="comment",
            name="nickname",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
