# Generated by Django 4.2.3 on 2023-07-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0019_alter_comment_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="user",),
    ]
